# Generated by Django 3.0 on 2020-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
                ('CIN', models.CharField(max_length=12)),
                ('adresse', models.CharField(max_length=50)),
                ('dateNaissance', models.DateField()),
            ],
        ),
    ]
