# Generated by Django 3.0 on 2020-01-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dab', '0001_initial'),
        ('Carte', '0002_auto_20200116_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Transaction', models.IntegerField()),
                ('type_Transaction', models.CharField(max_length=50)),
                ('date_Transaction', models.DateField()),
                ('id_Carte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carte.Carte')),
                ('id_Dab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dab.Dab')),
            ],
        ),
    ]
