# Generated by Django 3.0 on 2020-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_Transaction',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date de Transaction'),
        ),
    ]
