# Generated by Django 3.0 on 2020-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Carte', models.CharField(max_length=19)),
                ('code_Nip', models.IntegerField()),
            ],
        ),
    ]
