# Generated by Django 3.0 on 2020-01-16 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Compte', '0001_initial'),
        ('Type', '0001_initial'),
        ('Carte', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='id_Compte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Compte.Compte'),
        ),
        migrations.AddField(
            model_name='carte',
            name='id_Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Type.Type'),
        ),
    ]
