# Generated by Django 3.0 on 2020-02-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carte', '0003_carte_etat_carte'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='montant_Par_Mois',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='carte',
            name='nb_Par_Mois',
            field=models.IntegerField(),
        ),
    ]
