# Generated by Django 3.0 on 2020-02-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carte', '0005_auto_20200203_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='code_Nip',
            field=models.CharField(max_length=6),
        ),
    ]
