# Generated by Django 3.0 on 2020-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_Type', models.CharField(max_length=50)),
                ('limite_Montant', models.IntegerField()),
                ('limite_Transaction', models.IntegerField()),
            ],
        ),
    ]
