# Generated by Django 3.0 on 2020-02-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Type', '0002_auto_20200203_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='limite_Montant_Mois',
        ),
        migrations.RemoveField(
            model_name='type',
            name='limite_Transaction_Mois',
        ),
        migrations.AddField(
            model_name='type',
            name='limite_Montant_Semaine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='limite_Transaction_Semaine',
            field=models.IntegerField(null=True),
        ),
    ]
