# Generated by Django 3.0 on 2020-02-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Operateur', models.CharField(max_length=50)),
                ('prenom_Operateur', models.CharField(max_length=20)),
                ('telephone_Operateur', models.CharField(max_length=14)),
                ('email_Operateur', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('login', models.CharField(max_length=50)),
                ('mot_De_Pass', models.CharField(max_length=50)),
                ('date_Naissance_Operateur', models.DateField()),
            ],
        ),
    ]
