# Generated by Django 3.0 on 2020-02-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operateur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operateur',
            old_name='mot_De_Pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='operateur',
            old_name='login',
            new_name='username',
        ),
    ]
