# Generated by Django 3.0 on 2020-01-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_Agence', models.CharField(max_length=50)),
                ('code_Agence', models.CharField(max_length=10)),
                ('nom_Agence', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=50)),
                ('telephone_Agence', models.CharField(max_length=15)),
            ],
        ),
    ]
