# Generated by Django 3.0 on 2020-01-16 09:00

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('Agence', '0001_initial'),
        ('Client', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_Compte', models.CharField(max_length=20)),
                ('solde', models.IntegerField()),
                ('id_Agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agence.Agence')),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.Client')),
            ],
        ),
    ]
