# Generated by Django 3.0 on 2020-01-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ticket', '0001_initial'),
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_Transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.Transaction'),
        ),
    ]
