# Generated by Django 3.0 on 2020-02-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0002_auto_20200124_1702'),
        ('Dab', '0001_initial'),
        ('Carte', '0006_auto_20200208_1632'),
        ('Ticket', '0002_ticket_id_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_Carte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carte.Carte'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_Dab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dab.Dab'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_Transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Transaction.Transaction'),
        ),
    ]
